name: flutter-gallery
adopt-info: flutter-gallery
summary: Flutter Gallery
description: |
  A demo app for Flutter's material design and cupertino widgets, as well as many other features of the Flutter SDK.
grade: stable
confinement: strict
base: core18

architectures:
  - build-on: amd64

apps:
  flutter-gallery:
    command: bin/build
    extensions: [gnome-3-28]
    plugs:
      - opengl
    environment:
      __EGL_VENDOR_LIBRARY_DIRS: $SNAP/usr/share/glvnd/egl_vendor.d/

parts:
  flutter:
    plugin: nil
    # clone via override-build to preserve git meta
    override-build: |
      set -eux
      snapcraftctl build
      git clone -b master https://github.com/flutter/flutter.git
      flutter/bin/flutter config --enable-linux-desktop
      cp -r flutter $SNAPCRAFT_PART_INSTALL/
    build-packages:
      - git
      - unzip
      - curl
      - rsync
    prime:
      - -flutter

  patches:
    source: snap/local/patches
    plugin: dump
    prime:
      - -*

  flutter-gallery:
    after: [patches, flutter]
    source: https://github.com/flutter/gallery.git
    plugin: nil
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(git describe --tags --abbrev=10)
    override-build: |
      set -eux
      snapcraftctl build
      rm -rf linux
      $SNAPCRAFT_STAGE/flutter/bin/flutter channel master
      $SNAPCRAFT_STAGE/flutter/bin/flutter create --org io.flutter.examples .
      sed -i 's|build|Flutter Gallery|g' linux/window_configuration.cc
      patch -p1 < $SNAPCRAFT_STAGE/url_launcher_fde.patch
      $SNAPCRAFT_STAGE/flutter/bin/flutter pub get
      $SNAPCRAFT_STAGE/flutter/bin/flutter build linux --release -t lib/main.dart
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp -r build/linux/release/bundle/* $SNAPCRAFT_PART_INSTALL/bin/
    build-packages:
      - clang
      - cmake
      - ninja-build
    stage-packages:
      - libegl-mesa0
